### ISSUE TITLE
Incorrect IOOOB javadoc description

### ISSUE THREAD

**Issue by hugmanrique** [netty/netty-incubator-buffer-api#22]
Most methods that take absolute offsets in `BufAccessors` have an incorrect `@throws` clause. For example, `getByte` says
https://github.com/netty/netty-incubator-buffer-api/blob/1013c33c3ae5ab89e25813d98619e9da90d1fb11/src/main/java/io/netty/buffer/api/BufAccessors.java#L45-L46

Imagine a buffer with `capacity = 3` and let `offset = 2`. Then `buf.getByte(2)` will not throw, while the javadoc says `capacity - 1 = 2` "is" out of bounds. The correct wording would be _greater than_ instead (if `offset > 2`, then throw IOB).

This is a minor nit, and I would've PR a fix if I had the time 😛

**Comment by chrisvest** [comment]
Thanks!
