### ISSUE TITLE
Rc.get() must not acquire()

### ISSUE THREAD

**Issue by ejona86** [netty/netty-incubator-buffer-api#45]
Rc extends Deref and Suppler(!), so if passed a Deref/Suppler a caller may call get() and not be "in-the-know" that they need to call close(). In short, Rc _does not_ implement Deref/Supplier semantics. So either Rc should not extend Deref/Supplier or get() needs different behavior.

Note that it can be surprising if get() has side effects (like the call to acquire()).

**Comment by ejona86** [comment]
I don't know if this should be a separate issue, but it related to `get()` as well:

Deref is either broken or useless. Let's say I have a `Deref<?>` instance. I call `deref.get()`. That increased a reference count. But I have no way to decrement the reference! The javadoc has `Note:</strong> Callers must ensure that they close any references they obtain.` but T isn't defined strongly enough that it can be closed.

I'm also noticing that the semantics of `Deref` seem too weak to be a `Supplier`, because "Deref itself does not specify if a reference can be obtained more than once." whereas Suppliers you can call `get()` multiple times. At the very least it seems `get()` is missing documentation that it can throw `IllegalStateException` if called multiple times when unsupported.

Seems Send is also abusing `get()` in the same way as Rc. It isn't clear to me that Deref/Supplier are serving any purpose in the class hierarchy. I could understand if channel handlers were supposed to check for `instanceof Deref` instead of `instanceof Send`/`instanceof Buffer`, but I haven't yet noticed any code encouraging that (it's not a bad idea, but unless we encourage it it becomes useless).

**Comment by chrisvest** [comment]
Yeah, Deref might be causing more trouble than it's worth. It was added in order for buffer composition to take either buffers or sends. In hindsight I think it's a case of premature abstraction where a method overload could have worked just as well.

**Comment by chrisvest** [comment]
The Deref interface is gone in #51
