### ISSUE TITLE
Rename bifurcate to split

### ISSUE THREAD

**Issue by chrisvest** [netty/netty-incubator-buffer-api#52]
I was initially thinking that the `bifurcate` method would be advanced, rarely used API. Hence I decided to give it a somewhat obscure name. However, given the recent feedback and worked examples, it looks like this functionality might find use more often, in more situations, than I expected. I think, then, that it makes sense to give it a more approachable name, such as `split` or `splitAt`, as in splitting a buffer in two. There is prior art for that name, since the `Vec` type in Rust has a `split_at` method that does a similar thing.

What do people think?

/cc @normanmaurer @ejona86

**Comment by normanmaurer** [comment]
split(...) sounds good

**Comment by ejona86** [comment]
`split()` SGTM
