### ISSUE TITLE
Make send() faster and more efficient

### ISSUE THREAD

**Issue by chrisvest** [netty/netty-incubator-buffer-api#59]
The `send()` methods currently cause a number of object allocations in the way they are currently implemented. The implementation is general and convenient, but not necessarily optimal. I have come to realise that we can perhaps reduce the number of object allocations incurred by `send()` on a buffer, to just one.

The `send()` method returns a `Send<T>` object, and calling `receive()` on that produces a _new_ instance of the sent object. In the case of a buffer, the buffer that you call `send()` on effectively becomes inaccessible, as if it's been closed, in that moment.

If the buffer _implementation_ class (not the Buffer interface) implements the Send interface and its transfer mechanics, then it can make the inaccessible phase transition and return itself as a Send object. Calling `receive()` on that will then make the only necessary object allocation, that is the new buffer object. This new buffer object can then take over all the objects that represent the memory internally, the drop implementation, and any other data contained in the sent buffer.

**Comment by chrisvest** [comment]
We could go even further, if we have a system property (or some other sort of setting) that is opt-in and disables the safety provided by the send/receive mechanic. When enabled, each buffer could have a cached Send instance that simply returns the buffer reference when called. This makes the send/receive call pairs allocation-free.

**Comment by ejona86** [comment]
> Calling receive() on that

How will it manage "only-can-call-receive()-once"?

**Comment by chrisvest** [comment]
It won't. It'd be one of the safety things that be disabled.

**Comment by ejona86** [comment]
Reusing the backing buffer allocation for Send sounded like it wasn't wanting to give up the normal guarantees. That didn't sound like opt-in. I understand that the "We could go even further" option would be opt-in and can have greatly reduced guarantees.

**Comment by chrisvest** [comment]
Let's close this for now, because this is not used as often as anticipated, and the current performance doesn't appear to be an issue.
