### ISSUE TITLE
Rename `Rc` to `ReferenceCounted`

### ISSUE THREAD

**Issue by kashike** [netty/netty-incubator-buffer-api#69]
I did minimal searching before opening this issue, so my apologies if this has been discussed previously.

Currently this class (`Rc`) exists in Netty 4.1 as [`ReferenceCounted`](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/ReferenceCounted.java), but lost the descriptive name to something that I would call confusing: [`Rc`](https://github.com/netty/netty-incubator-buffer-api/blob/main/buffer-api/src/main/java/io/netty/buffer/api/Rc.java).

I would propose to rename this interface back to `ReferenceCounted`.

**Comment by kashike** [comment]
This can be closed if #70 is merged.

**Comment by chrisvest** [comment]
Plan is to remove the `Rc` interface in #70.

**Comment by franz1981** [comment]
It's nice to write less code IMO, why not RefCnt?
