### ISSUE TITLE
[Proposal] WritableByteCursor

### ISSUE THREAD

**Issue by astei** [netty/netty-incubator-buffer-api#76]
I propose adding an analogue to `ByteCursor`, but for writing to a buffer. In other words, where `ByteCursor` is similar to the common `Iterator` pattern, `WritableByteCursor` would be similar to a write-only `ListIterator`. Specifically, the guarantee would be similar to `ByteCursor` in that I am able to retrieve a cursor of the buffer that is guaranteed to be able to write exactly `n` bytes at the position I specify, like so (assuming a hypothetical VarInt writing method, which is one use case where this can be handy):

```java
public static void writeVarInt(Buffer buf, int value) {
  int byteSize = varIntBytes(value);
  WritableByteCursor cursor = buffer.openWriteCursor(byteSize);
  for (int i = 0; i < byteSize; i++) {
    // Use cursor here. byteSize bytes are guaranteed to be writable.
  }
}
```

I envision this being useful primarily for cases where minimal-to-no allocation (hopefully with the allocation subject to a scalar replacement or stack allocation by the JVM) is desirable and allocating a `byte[]` is undesirable (such as writing directly into a buffer).

**Comment by chrisvest** [comment]
I'm not seeing the benefit of this compared to calling `ensureWritable` or checking `writableBytes()`?
